#!/usr/bin/env python3
"""
Post-process a court filing docx generated by docx-js or manually drafted.

Dispatcher for modular patch architecture:
1. Runs universal core patches (all court types)
2. Optionally runs court-type-specific patches (e.g., NY caption styles)
3. Prints summary of operations performed

Usage:
    python patch_court_filing.py <unpacked_dir> [--court-type TYPE]

court-type options:
    tx-state    (default) Texas state district court
    ny-state    New York Supreme Court
    federal     U.S. District Court
    business    Texas Business Court

Backward compatibility:
    --court-type state → maps to tx-state
"""
import sys
import os
import argparse

from patch_core import run_core_patches
from patch_ny_state import run_ny_patches


def main():
    parser = argparse.ArgumentParser(
        description="Post-process court filing docx with universal and court-type-specific patches"
    )
    parser.add_argument(
        "unpacked_dir",
        help="Path to unpacked docx directory"
    )
    parser.add_argument(
        "--court-type",
        default="tx-state",
        help="Court type: tx-state (default), ny-state, federal, business, aaa-arb. 'state' maps to tx-state for backward compat."
    )

    args = parser.parse_args()
    unpacked_dir = args.unpacked_dir
    court_type = args.court_type

    if not os.path.isdir(unpacked_dir):
        print(f"ERROR: unpacked_dir does not exist: {unpacked_dir}", file=sys.stderr)
        sys.exit(1)

    if court_type == "state":
        court_type = "tx-state"
        print("NOTE: --court-type 'state' mapped to 'tx-state' (backward compat)")

    # Validate court type
    valid_types = ["tx-state", "ny-state", "federal", "business", "aaa-arb"]
    if court_type not in valid_types:
        print(f"ERROR: invalid court-type '{court_type}'. Valid: {', '.join(valid_types)}", file=sys.stderr)
        sys.exit(1)

    print(f"\nPatchin court filing: {court_type}")
    print("=" * 60)

    core_results = run_core_patches(unpacked_dir, court_type=court_type)

    ny_results = None
    if court_type == "ny-state":
        print()
        ny_results = run_ny_patches(unpacked_dir)

    print("\n" + "=" * 60)
    print("Summary:")
    print(f"  Court type: {court_type}")
    print(f"  Styles patched: {core_results['styles_patched']}")
    print(f"  Numbering patched: {core_results['numbering_patched']}")
    print(f"  Document patched: {core_results['document_patched']}")
    if core_results['num_id']:
        print(f"  NumId assigned: {core_results['num_id']}")
    if ny_results:
        print(f"  NY caption styles injected: {ny_results['styles_count']}")
    print("=" * 60)


if __name__ == "__main__":
    main()
